#!/usr/bin/env node

const { spawnSync } = require('child_process')
const { status } = spawnSync('standard', ['--fix', 'src/*.js', 'src/**/*.js', 'scripts/*', 'tests/*.js'], {
  stdio: 'inherit'
})
process.exit(status)
