#!/usr/bin/env node

console.time('test')
const { spawnSync } = require('child_process')
const { status } = spawnSync('ava', ['-c100', 'tests/*.test.js'], {
  stdio: 'inherit'
})
console.timeEnd('test')
process.exit(status)
